### ISSUE TITLE
Support for rounded corners and blurred as with kde 5.25

### ISSUE THREAD

**Issue by Shaurya-Kalia** [kupiqu/SierraBreezeEnhanced#105]
Will the theme be updated to support kde 5.25?

**Comment by kupiqu** [comment]
Sorry, no free time available. If somebody wants to submit a pull request, that would be great.

**Comment by kupiqu** [comment]
Fixed with #107

**Comment by Shaurya-Kalia** [comment]
That was quick. Thanks to you and @a-parhom

**Comment by kupiqu** [comment]
Thanks to @a-parhom, who did the work :)
