### ISSUE TITLE
Opacity of title bar and window borders do not match when it is not 0% or 100%

### ISSUE THREAD

**Issue by CAG2Mark** [kupiqu/SierraBreezeEnhanced#108]
I'm not sure whether this is KDE bug or a bug with this theme, but it seems that the opacity of the borders are different from the opacity of the title bar when the opacity is not 0% or 100%. See the image below - I have the opacity set to 70%. I've intentionally made the borders extremely large so it is clear what the issue is. (Screenshot on Plasma 5.25)

![image](https://user-images.githubusercontent.com/55091936/178037300-a8ddba7a-f409-4e88-8905-0a2c9d17aeb3.png)

I did have a look around the code and could not find anything obvious that could cause this, though I am not terribly familiar with how Breeze window decorations work. If someone more familiar could find the cause, that would be nice.

**Comment by kupiqu** [comment]
It seems to be an issue with `painter->drawRoundedRect`, no idea why. I guess a KDE/Qt issue

**Comment by kupiqu** [comment]
I think I fixed it. Will push a new version later Today
