### ISSUE TITLE
"Match title bar color to window color" option does not take effect

### ISSUE THREAD

**Issue by in-depth-1** [kupiqu/SierraBreezeEnhanced#109]
When I enable this option, when the window color is black, the title bar does not take effect. As shown in the screenshot, there is a window about my black theme, it does not follow the color change, what can I do to make it take effect?

![图片](https://user-images.githubusercontent.com/62343478/185776930-698f4bd8-e7aa-4d79-a1af-47a7b915ca91.png)
![图片](https://user-images.githubusercontent.com/62343478/185776953-23fcd137-e26e-4439-a7d1-1a747c05b603.png)
![图片](https://user-images.githubusercontent.com/62343478/185776975-1fad39ff-66aa-4647-b654-d5a27886f69b.png)

**Comment by kupiqu** [comment]
Even though your windows appear black, for KDE (kwin) they are not. What you need to do is either one of the following two options:

- Change the color theme to a dark one that you may like (note this will change the theme for all the applications controlled by kwin)

- Specify the color theme that you want to apply to your dark appearing applications (note that this will leave other applications untouch)
