### ISSUE TITLE
Left vs. right unison hovering

### ISSUE THREAD

**Issue by kupiqu** [kupiqu/SierraBreezeEnhanced#110]
Hey @trmdi,

I hope I find you well...

So I was fixing some SBE bugs in very spare time that I had for two days before coming back to business ;) 

I wonder if you'd have some time and would like to contribute further to SBE by improving unison hovering, in particular making it independent for left and right buttons. I think it would look cooler. I am not 100% sure but I think this may be how it works in macOS...

It could be done using two new flags, for left vs. right buttons, similarly to the current flags: FlagFirstInList and FlagLasttInList.

Thanks and best

**Comment by kupiqu** [comment]
Sorry @trmdi, it seems we had this discussion already

**Comment by trmdi** [comment]
No problem. Glad to know that you're still maintaining it.
Best! :)
