### ISSUE TITLE
"Match Title Bar to Window Colour" option not working correctly. 

### ISSUE THREAD

**Issue by linusrg1** [kupiqu/SierraBreezeEnhanced#112]
If this option is enabled the only windows where the title bar matches the colour of the window is popup windows, but not the main applications themselves. (GTK or QT) But if the option is disabled, the title bar of main application windows matches the colour of the window itself, but popup windows don't.  

Option disabled: 
![TitleBarMatch_OFF](https://user-images.githubusercontent.com/67347319/196011630-b93b935d-4a67-4445-a0e2-52a35a420173.jpg)
![TitleBarMatchOFF2](https://user-images.githubusercontent.com/67347319/196011631-2a82271a-2807-4cae-8600-a23813555b39.jpg)

Option enabled: 
![TitleBarMatch_ON](https://user-images.githubusercontent.com/67347319/196011657-1c05cc14-8b41-410b-a3b2-094e6d70af56.jpg)
![TitleBarMatch_ON2](https://user-images.githubusercontent.com/67347319/196011658-19a9de94-4273-468b-8324-f885b07c1743.jpg)

Software Info: 
Operating System: openSUSE Tumbleweed 20221014
KDE Plasma Version: 5.26.0
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.6
Kernel Version: 6.0.1-1-default (64-bit)
Graphics Platform: Wayland

**Comment by kupiqu** [comment]
duplicate, see #109
