### ISSUE TITLE
Option to set border lines for enhanced contrast

### ISSUE THREAD

**Issue by RichGuk** [kupiqu/SierraBreezeEnhanced#12]
Not too sure if currently possible but is there anyway to add an option for having a 1px contrast border around windows in addition to shadows. Like this https://github.com/ishovkun/SierraBreeze/issues/34#issuecomment-424166421.

Its a subtle change, but it makes windows ever so slightly easier to see when on top of each other:

![shot1](https://i.imgur.com/VSoyS42.png)

vs

![shot2](https://i.imgur.com/QJxLxtU.png)

**Comment by Luwx** [comment]
@kupiqu Do you know if it's possible to have this line **inside** the window?

**Comment by kupiqu** [comment]
> @kupiqu Do you know if it's possible to have this line **inside** the window?

I wonder why you are asking? I have only thought about doing it outside so far, as an additional, mostly hard-coded, shadow that acts as an extra "line", which can be enabled/disabled and changed its color, but not its, strength, size and opacity.

I haven't had time to look at it yet, but naively enough I now think there may be two ways to do it:

- "inside" the window: by manipulating the color of the border (either in the color scheme or in the decoration), or adding an extra "line" in addition to the border that does this (in the decoration, so one can have both, the borders and the extra line).

- "outside" the window: by manipulating the color, strength and size of the shadow (already implemented), or adding an extra "line" in addition to the shadow for this (so one can have both, the shadow and the extra line).

@Luwx, @RichGuk, would you have any preference and a clear reason for it? I'd like to decide on this before attempting its implementation...

Perhaps the easiest is to replicate the behavior of the separator between the title and the window for such a contrast "line". 

Thinking about it, it may also be useful to allow users to easily edit the color of that separator line in the decoration properties.

**Comment by Luwx** [comment]
> I wonder why you are asking?

That's how it's done in Mojave. They have two lines (3 in HiDPI), one outside the window (much darker compared to what breeze has now) and a bright semi-transparent one inside.

![screenshot_20181209_192604](https://user-images.githubusercontent.com/33076480/49704022-54e9ca80-fbf4-11e8-9c22-22255fd2237e.png)


I tried to replicate this myself, but I could only manage to have the white line behind the window content, which is not useful.

Anyway, I would be in favor of just hardcode the strengh value, as this makes overlapping content in dark themes easier to distinguish (default shadow color not being black does not help), but some users may find it too distracting.. so a option like: " [ x ] Use dark outline arround the window " should please everyone.

**Comment by kupiqu** [comment]
Potentially relevant info below (from krohnkite README https://github.com/esjeon/krohnkite)... I can simply adjust these colors as I do with the titlebar background...

### Changing Border Colors ###

Changing the color of borders makes it easier to identify the currently focused
window.  This is quite an essential if title bars are removed.

1. Open `~/.config/kdeglobals` with your favoir editors. (i.e. Kate, Vim, Nano)
2. Scroll down and find `[WM]` section
3. Below the section, append the followings:
    - `frame=61,174,233`: set the border color of active window to *RGB(61,174,233)*
    - `inactiveFrame=239,240,241`: set the border color of inactive window to *RGB(239,240,241)*
4. You must **restart** your session to see changes. (i.e. re-login, reboot)

(Note: the RGB values presented here is for the default Breeze theme. Feel free
to change these values. You can use [KColorChooser][] to pick colors from the
screen.)

[KColorChooser]: https://www.kde.org/applications/graphics/kcolorchooser/

**Comment by kupiqu** [comment]
If anyone wants to give it a try, contributions wanted ;)

**Comment by kupiqu** [comment]
Fixed with 34f9acc09ef10558d29a264df69a9d74e8fd17af
