### ISSUE TITLE
Rounded corners bug

### ISSUE THREAD

**Issue by ericmacedo** [kupiqu/SierraBreezeEnhanced#121]
I'm facing this bug when I enable rounded corners:
![image](https://user-images.githubusercontent.com/8262322/235535067-07d29761-ef31-4d0c-a80e-bd030b715983.png)

The rounding corners affect the whole title bar, even the bottom corners.

Specs:
- Distro: openSUSE Tumbleweed x86_64
- Kernel: 6.2.12-1-default
- Plasma 5.27.4
- Plasma widget style: Kvantum
- Kvantum Manager: 1.0.10
- Kwin_X11: 5.27.4

I think is worth mentioning that I'm also using [LightlyShaders](https://github.com/a-parhom/LightlyShaders) to enable rounded corners on windows. However, even when I disable it, the problem persists.

Thanks in advance, and for your hard work.

**Comment by kupiqu** [comment]
if you are interested in rounded corners you should probably use https://github.com/a-parhom/RoundedSBE

**Comment by ericmacedo** [comment]
Same problem...
![image](https://user-images.githubusercontent.com/8262322/235707737-a203a6d8-90c6-4465-8d7d-a843f5969b1b.png)

**Comment by mojolo** [comment]
Confirmed same bug on Kubuntu with both SBE and Rounded SBE.

Distro: Kubuntu 23.04
Plasma: v5.27.4
Qt: v5.15.8
Windowing: Kwin X11

**Comment by mojolo** [comment]
Nevermind. 
Per @a-parhom, we have to disable borders:

`System Settings > Window Decorations> Window border size > No Borders`

See [RoundedSBE Corners bug #6](https://github.com/a-parhom/RoundedSBE/issues/6)

**Comment by kupiqu** [comment]
Indeed. It seems it is a problem of kwin
