### ISSUE TITLE
Failed to match the exception on wayland

### ISSUE THREAD

**Issue by A1ca7raz** [kupiqu/SierraBreezeEnhanced#124]
The exception rules failed to match the window class on wayland, which works on xorg and the official breeze windeco with wayland. It can match by the window name.
And the detect button disappeared on wayland.
Sierra:
![图片](https://github.com/kupiqu/SierraBreezeEnhanced/assets/7345998/21a0aba5-d434-49ec-a1bd-ee04f6133673)
Breeze:
![图片](https://github.com/kupiqu/SierraBreezeEnhanced/assets/7345998/cc484875-6b1f-45ea-83d5-be98e55be50f)

- Sierra: 1.3.3
- Distro: NixOS unstable
- Kernel: 6.1.49
- Plasma 5.27.7
- Plasma widget style: Kvantum
- Kvantum Manager: 1.0.10
- Kwin_wayland: 5.27.7

**Comment by A1ca7raz** [comment]
Maybe official breeze works because of [this](https://bugs.kde.org/show_bug.cgi?id=399763).

**Comment by kupiqu** [comment]
You fixed it! Available in Version 2.0.0
