### ISSUE TITLE
Add option to control titlebar's size

### ISSUE THREAD

**Issue by Petross404** [kupiqu/SierraBreezeEnhanced#13]
When using SierraBreezeEnhanced without borders, the titlebar seems non-optimal sized. It would be nice if an option could make the titlebar slimmer.

Any thoughts?

**Comment by kupiqu** [comment]
Screenshot? 

Is it any different when using vanilla Breeze or Breeze Enhanced or Sierra Breeze?

**Comment by kupiqu** [comment]
I just checked without borders and see no issue.

One thing you can try is making the buttons smaller.

**Comment by Petross404** [comment]
![screenshot_20181207_225748](https://user-images.githubusercontent.com/18561627/49672192-0103a800-fa73-11e8-8a67-171838b1d64b.png)
![screenshot_20181207_225917](https://user-images.githubusercontent.com/18561627/49672194-0103a800-fa73-11e8-9869-fddd04552499.png)

I suppose you are right, the font is kind of big. Anyway, thanks.

**Comment by kupiqu** [comment]
> I suppose you are right, the font is kind of big. Anyway, thanks.

You can change the font size (and style). You know that, right?
