### ISSUE TITLE
Plasma button hover broken on Arch/CachyOS

### ISSUE THREAD

**Issue by OzzyHelix** [kupiqu/SierraBreezeEnhanced#141]
when I have the plasma icons enabled I get really broken looking animations on hover I just wanted to ask if this is a known problem also there was an update to Plasma 6.2.3 and some stuff broke I think

https://github.com/user-attachments/assets/29ace1ab-1fda-467f-89d8-ccc4260cf058

![image](https://github.com/user-attachments/assets/c2706292-9354-45da-8e40-eb99befd47ad)

![image](https://github.com/user-attachments/assets/32e5e90e-0f0e-4286-b119-09344f2a05c6)

**Comment by kupiqu** [comment]
Weird. It works fine in my system

**Comment by OzzyHelix** [comment]
all the buttons shouldn't be lighting up with plasma this is what the normal breeze plasma theme does 

https://github.com/user-attachments/assets/9808023f-15e8-41c6-b08e-7ef7dcbf4d71

**Comment by kupiqu** [comment]
This is how it works for me. There is a setting "unison hovering" that makes hover all in sync, but even if I enable that feature, it works as expected without weird animations
