### ISSUE TITLE
Option to specify titlebar background color (and port it to overrides)

### ISSUE THREAD

**Issue by kupiqu** [kupiqu/SierraBreezeEnhanced#17]
This would ease significantly matching the color of applications that do not follow the color scheme, e.g. konsole, qview, browsers, libreoffice, gtk applications...

**Comment by Petross404** [comment]
> This would ease significantly matching the color of applications that do not follow the color scheme, e.g. konsole, qview, browsers, libreoffice, gtk applications...

I implemented an option to match the window's and titlebar's color [here](https://github.com/ishovkun/SierraBreeze/issues/40). If that's what you are asking for let me know if I can help. SierraBreeze can match konsole's and titlebar based on [konsolerc](https://github.com/ishovkun/SierraBreeze/blob/master/breezedecoration.cpp#L305).

Also are you sure that you can read the window's color of a GTK app?

**Comment by kupiqu** [comment]
> I implemented an option to match the window's and titlebar's color here.

This is already implemented. What this issue is actually about is to set a particular color without having to mess with kde colors and kwin rules.

**Comment by Petross404** [comment]
Something like a QColorDialog to select a color?

**Comment by kupiqu** [comment]
> Something like a QColorDialog to select a color?
Yes

**Comment by kupiqu** [comment]
If anyone wants to give it a try, contributions wanted ;)

**Comment by kupiqu** [comment]
I suggest using https://github.com/ArturGaspar/kwin_auto_titlebar_colours to automatize this... closing the issue
