### ISSUE TITLE
Remove @ from version numbering in releases

### ISSUE THREAD

**Issue by Appadeia** [kupiqu/SierraBreezeEnhanced#2]
Using a `@` in the version numbering prevents Open Build Service from building this.
![image](https://user-images.githubusercontent.com/20326855/48974051-63908900-f01b-11e8-969d-68e2ee24b3be.png)
Also, literally no repo that I can think of off the top of my head will take this style of version number

**Comment by kupiqu** [comment]
Oops, sorry about that, will fix it...

**Comment by kupiqu** [comment]
Done

**Comment by kupiqu** [comment]
Btw, this should be built as SierraBreezeEnhanced, not as BreezeEnhanced:

![image](https://user-images.githubusercontent.com/20326855/48974051-63908900-f01b-11e8-969d-68e2ee24b3be.png)
