### ISSUE TITLE
Feature Request: Toggle to Swap Okay and Cancel Buttons

### ISSUE THREAD

**Issue by sockusminimus** [kupiqu/SierraBreezeEnhanced#20]
In macOS, the Okay and Cancel buttons are swapped compared to the platform default on KDE.  I am not sure if it's possible to override this in a theme.  If it is, it would be awesome to be able to change the default button layout in modal dialogs to be selectable from Windows, KDE, GNOME and Mac OS X as it is in qt5ct.

It looks like qt5ct does it this way in the code:
    m_ui->buttonLayoutComboBox->addItem("Windows", QDialogButtonBox::WinLayout);
    m_ui->buttonLayoutComboBox->addItem("Mac OS X", QDialogButtonBox::MacLayout);
    m_ui->buttonLayoutComboBox->addItem("KDE", QDialogButtonBox::KdeLayout);
    m_ui->buttonLayoutComboBox->addItem("GNOME", QDialogButtonBox::GnomeLayout);

....

void InterfacePage::writeSettings()
{
    QSettings settings(Qt5CT::configFile(), QSettings::IniFormat);
    settings.beginGroup("Interface");
    ....
    settings.setValue("buttonbox_layout", m_ui->buttonLayoutComboBox->currentData());
    ....
}

**Comment by kupiqu** [comment]
Sorry, but this feature request should be considered upstream.
