### ISSUE TITLE
Configurable padding for titlebar (especially relevant for Gnome-theme)

### ISSUE THREAD

**Issue by ripefig** [kupiqu/SierraBreezeEnhanced#22]
to get a bigger titlebar right now, you need to scale up the button glyphs. Huge glyphs look pretty bad. I think it would be nice to be able to increase the size of the titlebar and buttons without increasing the size of the glyphs:

![2](https://user-images.githubusercontent.com/45201036/50460606-8d293100-0988-11e9-9f17-e37a68037364.gif)

**Comment by kupiqu** [comment]
Closing for lack of interest. I'm open to review a pull request

**Comment by kupiqu** [comment]
I'm reconsidering this

**Comment by kupiqu** [comment]
relevant commit 975d5df1367b44faadc87cd7c172fe0846ec878b

**Comment by kupiqu** [comment]
I implemented the padding, will push it soon

**Comment by kupiqu** [comment]
fixed 2ad2bdd7a897a7507f0f0aba337aeb5ce47f2d12
