### ISSUE TITLE
Add outline to close, minimize and maximum buttons aka traffic lights.

### ISSUE THREAD

**Issue by arun54321** [kupiqu/SierraBreezeEnhanced#23]
Could you add a variant with circular outline on traffic lights like Mac OS? It is already in several aurorae themes like breezemite.

![Sample](https://i.allthepics.net/close_min_max.png)

**Comment by kupiqu** [comment]
There is a theme that is very similar to this one. Not sure it makes much sense to add a new one that is almost the same, perhaps better to adapt the previous to this.

How should I interpret the third column? I guess it's the clicked status (I assume the first is the default status and the second is the hovered status). Can you confirm?

Is this only about the outline or also about the icon symbol color? I kind of like the outline, but I'm not so sure about the symbol color...

**Comment by arun54321** [comment]
Please ignore the third column. I like to have outline like this. No need to change glyph color.

![traffic](https://i.allthepics.net/dribbb-1.png)

**Comment by kupiqu** [comment]
That sounds good and should be an easy change.

**Comment by kupiqu** [comment]
This should be rather simple thing to do. If anyone wants to give it a try, contributions wanted ;)
