### ISSUE TITLE
Option to set title bar side

### ISSUE THREAD

**Issue by KonqiTheKonqueror** [kupiqu/SierraBreezeEnhanced#27]
It would be great if there were an option to configure what side the title bar is on, e.g. the left, or the bottom, right, or top (as usual).
KDecoration2 supports this, so it's up to the decoration to add the functionality.

**Comment by kupiqu** [comment]
I don't have much time to work on this anymore, but feel free to contribute to the project

**Comment by kupiqu** [comment]
Sorry, not interested, but I'm open to review a pull request
