### ISSUE TITLE
Titlebuttons on hover

### ISSUE THREAD

**Issue by gabrielfern** [kupiqu/SierraBreezeEnhanced#28]
It would be cool if it had an option to remove the effect on hover (not becoming bigger) on macOS-like titlebuttons
![macOS-like titlebuttons](https://github.com/kupiqu/SierraBreezeEnhanced/blob/master/screenshots/ActiveButtons.gif?raw=true)

And another option to not have the colored cicles on hover in the other style of titlebuttons
![not macOS-like titlebuttons](https://github.com/kupiqu/SierraBreezeEnhanced/blob/master/screenshots/InactiveButtons.gif?raw=true)

**Comment by kupiqu** [comment]
As mentioned in the reddit thread, I think the best way for these and other options to be implemented is by first refactoring the set of options. 

If the community behind SBE would grow, this could be done in a collaborative way, but unfortunately I don't have much time as before to go through this just by myself right now.

**Comment by kupiqu** [comment]
> It would be cool if it had an option to remove the effect on hover (not becoming bigger) on macOS-like titlebuttons

Just disable animations

**Comment by kupiqu** [comment]
fixed with commit 3d87361e8f5743a2e69c8fb69bdfed1408773993
