### ISSUE TITLE
Add prerequisite packages to build information

### ISSUE THREAD

**Issue by parzivail** [kupiqu/SierraBreezeEnhanced#29]
If you're building this repo in a clean install of KDE, you'll need:

    sudo apt-get install libkf5coreaddons-dev libkf5guiaddons-dev libkf5configwidgets-dev libkf5windowsystem-dev libkf5i18n-dev libqt5x11extras5-dev qt5-default extra-cmake-modules libkdecorations2-dev

**Comment by kupiqu** [comment]
Not sure how relevant is this, as it is only for a deb system, and there's a ppa repo for it.
