### ISSUE TITLE
Any way to apply inactive window buttons to all windows?

### ISSUE THREAD

**Issue by Fairlight8** [kupiqu/SierraBreezeEnhanced#3]
Maybe this is contraproducent as I saw that you no longer support non macOS buttons, but I really like the inactive window buttons, with the 1px circle, and the silhouette. Is there any way that I can use them in all the windows, changing something in the source? 
Thanks for your time!

**Comment by kupiqu** [comment]
I don't know what exactly you mean. Do you have a screenshot to show it?

**Comment by kupiqu** [comment]
Not sure there is much of a need for implementing this. Why not using BreezeEnhanced or any other minimalistic kwin decoration style instead?

**Comment by Fairlight8** [comment]
I mean, the exact behavior in the inactive windows, like the write screenshot in your readme.md.

I understand that it's not a popular request, so I ask if I can do it myself, and not bother anyone.

I ask because BreezeEnhanced isn't the same, has static buttons (that I like, but your details are better in my opinion), and because it is bugged for medium size button, that I use.

**Comment by kupiqu** [comment]
Oh, I see, you want a kwin decoration style that behaves exactly like current one for inactive windows but applied to all windows, i.e., including the active one.

I think I could set an option to use default current behavior or alternatively, active or inactive behavior for all.

I will try to do it, but tagging this as low priority. I hope it sounds good.

**Comment by Fairlight8** [comment]
Sure thing! Thanks a lot!
I hope that I am not the only one that would like that feature :P

**Comment by kupiqu** [comment]
fixed with commit b3cb7b4ac13017eab8292fdeecc35b04ec0b4fa3

**Comment by kupiqu** [comment]
This was easier to implement than I expected. Enjoy! :)

**Comment by Fairlight8** [comment]
Just updated it, and looks awesome!! Thanks a lot!!
