### ISSUE TITLE
Installed but not showing under Window Decorations

### ISSUE THREAD

**Issue by xidiot** [kupiqu/SierraBreezeEnhanced#31]
After following the steps for compiling SierraBreezeEnhanced is not shown under System Settings > Application Style > Window Decoration . I've even restarted (beside the logout) the laptop 2 times without success.

OS: Fedora 30 (Thirty)
kernel: 5.2.17-200.fc30.x86_64
$ kwin --version
kwin 5.15.5

**install_manifest.txt** content:

/usr/lib64/qt5/plugins/org.kde.kdecoration2/sierrabreezeenhanced.so
/usr/share/kservices5/sierrabreezeenhancedconfig.desktop
/usr/lib/libsierrabreezeenhancedcommon5.so.0.4.7
/usr/lib/libsierrabreezeenhancedcommon5.so.0

Let me know if anything else is needed. I've saw that another user is also facing thing malfunction - https://www.reddit.com/r/kde/comments/acwinn/sierra_breeze_enhanced_v045/edlxs7f/

**Comment by kupiqu** [comment]
Sorry but I have no idea what the issue might be

**Comment by kupiqu** [comment]
For the case it is useful, in kde neon user edition, I do:

```
cmake .. -DCMAKE_INSTALL_PREFIX=`kf5-config --prefix=` -DKDE_INSTALL_QTPLUGINDIR=/usr/lib/x86_64-linux-gnu/qt5/plugins -DKDE_INSTALL_LIBDIR=x86_64-linux-gnu/qt5  -DCMAKE_BUILD_TYPE=Release -Wnodev`
make
sudo make install
```

**Comment by kupiqu** [comment]
Is there any error/warning you see in the output of these commands?

**Comment by kupiqu** [comment]
Closing for lack of response
