### ISSUE TITLE
Option for borders to use titlebar color

### ISSUE THREAD

**Issue by cupnoodles14** [kupiqu/SierraBreezeEnhanced#35]
Hello! I think it would be nice to have an option for borders to match titlebar color. This is a default look in BreezeEnhanced, and it cannot be achieved anymore. Currently it's possible for titlebar to use border colors but not vice versa.

Current SierraBreezeEnhanced (it's either this, or titlebar gets gray too):

![Screenshot_20191120_105754](https://user-images.githubusercontent.com/29466521/69219973-0e7f4880-0b85-11ea-881e-3480a7ee562c.png)

Proposed option (like BreezeEnhanced):

![Screenshot_20191120_105703](https://user-images.githubusercontent.com/29466521/69220165-6a49d180-0b85-11ea-9455-95b19b69ab27.png)

I think these lines have something to do with it:
https://github.com/kupiqu/SierraBreezeEnhanced/blob/b34f9c1edb08901b78b233356d1112becd9c7cd7/breezedecoration.cpp#L686-L691

And changing them to something like that fixes the issue for me, except it doesn't add actual options for other people :) (sorry it's not a pull request):
```cpp
if ( matchColorForTitleBar() ) {
    m_windowColor = titleBarColor;
}
else {
    if (borderColorMatchesTitleBar) {
        m_windowColor = titleBarColor;
    }
    else {
        m_windowColor = c->color( c->isActive() ? ColorGroup::Active : ColorGroup::Inactive, ColorRole::Frame );
    }
}
```
Or maybe 
https://github.com/kupiqu/SierraBreezeEnhanced/blob/b34f9c1edb08901b78b233356d1112becd9c7cd7/breezedecoration.cpp#L676
is a better place for that.

**Comment by n4n0GH** [comment]
It's pretty simple, actually. All it requires is setting up a new config option and then having a check for whether or not the borders should be colored differently:

``` C++
if ( !borderColors() ){ // checks if borders should _not_ have custom colors
    painter->setBrush( c->color( c->isActive() ? ColorGroup::Active : ColorGroup::Inactive, ColorRole::Frame )
    } else { painter->setBrush( this->titleBarColor() ); } 
```
