### ISSUE TITLE
Option for monocolor inactive titlebar buttons

### ISSUE THREAD

**Issue by origamiman72** [kupiqu/SierraBreezeEnhanced#37]
It would be great if the macos style buttons would turn monocolor (but stay as circles) when the window is inactive instead of turning into icons that aren't circles (like macos).

**Comment by kupiqu** [comment]
Sorry, but I personally don't like uninformative monocolor circles

**Comment by kupiqu** [comment]
There are other themes out there that do exactly what you want. Mine is not really meant to be a Mac clone

**Comment by krisives** [comment]
If anyone is wanting this effect try https://github.com/n4n0GH/hello/

**Comment by kupiqu** [comment]
I actually made it in V0.7.0
