### ISSUE TITLE
Feature Request: No shadow on inactive windows?

### ISSUE THREAD

**Issue by Dr-Ongo** [kupiqu/SierraBreezeEnhanced#4]
Would it be possible to have an option for shadow to be only on the focused window? This would make it more obvious which window is focused and give the desktop a greater feeling of depth.

**Comment by kupiqu** [comment]
I tried the feature and doesn't look nice. I think I will instead optionally allow for Small instead of Large Shadows applied to inactive windows.

**Comment by kupiqu** [comment]
This is basically done, but I have an issue with shadows not being applied directly to all windows when reverting same shadows for all. Holding the horses until l figure out what's going on.

**Comment by Dr-Ongo** [comment]
Awesome. Thanks for all your work!

**Comment by kupiqu** [comment]
Fixed with commit 9673c5e1f1b7e0aeb7e1655bb6840e03fe6614ba
