### ISSUE TITLE
Titlebar gradient is inverted.

### ISSUE THREAD

**Issue by ripefig** [kupiqu/SierraBreezeEnhanced#41]
This is Sierra breeze enhanced:
![image](https://user-images.githubusercontent.com/45201036/69855331-5b0d0700-129c-11ea-8c57-9c2905881e1d.png)

And this is Breeze enhanced, which has what I'd consider a normal gradient (closer to Mac OS too):
![image](https://user-images.githubusercontent.com/45201036/69855276-39138480-129c-11ea-984e-07caac5c8397.png)

**Comment by kupiqu** [comment]
IMO there's not such a thing like a "normal" gradient, and if it was, IMO it would be that that allows smooth transitions, which is the point here. 

Given the shadows, etc., I think it makes sense that in light themes, gradient goes dark to light, and this to be re reversed for dark themes.

And sorry, but this is the case also in Breeze.

**Comment by kupiqu** [comment]
On a second thought, perhaps I could make an option for it, but there are many already :/

I'll leave it open...

**Comment by kupiqu** [comment]
I try to improve this but unfortunately I can only see gradient effects when the composition is off. Somehow shadows masked this to me before. Can you please confirm that you see gradients in Sierra Breeze Enhanced working properly (regardless of the direction of it) when composition is on in your system?

**Comment by ripefig** [comment]
Composition is on, so yes they work properly. But it looks weird due to the direction of the gradient. Breeze has the "normal" direction of the gradient that goes light -> normal, to simulate a light shining on a 3d object from the top.

**Comment by kupiqu** [comment]
Would you mind sharing a screenshot of your sierra breeze enhanced settings?

**Comment by kupiqu** [comment]
> Would you mind sharing a screenshot of your sierra breeze enhanced settings?

Ok, found out. There was a bug that I fixed

**Comment by kupiqu** [comment]
Fixed with commit 2324695
