### ISSUE TITLE
Improve the titlebar separator

### ISSUE THREAD

**Issue by ripefig** [kupiqu/SierraBreezeEnhanced#42]
The default Breeze separator doesn't look good IMO:
![image](https://user-images.githubusercontent.com/45201036/69855761-43824e00-129d-11ea-94fa-f354a48741ee.png)

I think this is a much better separator IMO, and it's similar to Mac OS and other mainstream styles. Note how it also appliies to inactive windows.
![image](https://user-images.githubusercontent.com/45201036/69855637-f8683b00-129c-11ea-91e7-059f8f99851a.png)

(taken from https://github.com/n4n0GH/hello/)

**Comment by kupiqu** [comment]
Yes, that's easy and looks nice

**Comment by kupiqu** [comment]
Also, having second thoughts on the titlebar vertical spacing :/

**Comment by kupiqu** [comment]
This is done, but dealing with the gradient etc before I push this

**Comment by kupiqu** [comment]
Fixed with commit 2324695
