### ISSUE TITLE
[Feature request] Display hint of all buttons when hovering on any one

### ISSUE THREAD

**Issue by trmdi** [kupiqu/SierraBreezeEnhanced#43]
Do you like this? See https://www.youtube.com/watch?v=gdGr_ZiocW4 at 0:10

![image](https://user-images.githubusercontent.com/11857205/69878968-d7cdce80-12f8-11ea-9454-69a9fedd582f.png)

I think it's a nice behavior of macOS.

**Comment by kupiqu** [comment]
Oh, you mean to show all symbols when any one of them is hovered, right?

**Comment by trmdi** [comment]
Yes, it meant that. :)

**Comment by psifidotos** [comment]
ping, here as reference from https://github.com/kupiqu/SierraBreezeEnhanced/pull/45#issuecomment-559928098

**Comment by kupiqu** [comment]
Thanks @trmdi for your contribution!

**Comment by kupiqu** [comment]
Not sure why but I couldn't apply the unison hovering to color/monochrome symbols (sierra and dark aurorae). I tried adding hovering conditionals over there, but they only seem to work for modifying the pen and fail to be applied to the brush :(

**Comment by trmdi** [comment]
Just upgraded to the latest commit and I notice that hovering on buttons of inactive windows does not show the symbols. Maybe you did something wrong?

**Comment by kupiqu** [comment]
Mmm, it works for me.

Can you share a screenshot of your options to test?

**Comment by trmdi** [comment]
Ah, it depends on the window color scheme?

**Comment by kupiqu** [comment]
Not in my head right now, could you share your settings and color scheme for me to test?

**Comment by trmdi** [comment]
When I use "Match titlebar to Window color" && KvMojave color for the titlebar, the symbols are very difficult to see. Is it a feature or a but?

**Comment by trmdi** [comment]
I think the color of the button doesn't depend on the window color => the symbol shouldn't depend on it too. So I guess this is a bug?

**Comment by kupiqu** [comment]
I can reproduce, but please open a new issue for it, as it is unrelated to this issue.

**Comment by trmdi** [comment]
Sure.

**Comment by kupiqu** [comment]
@trmdi a completely unrelated thing and naive question, I see a plus symbol in the green button of the video you posted? Is this current macOS maximization symbol or something else? And if it is, is it changing for maximized windows? Just wondering if SBE should adapt to it, or not. What do you think?

**Comment by trmdi** [comment]
I'm not sure. I've asked the question here: https://www.reddit.com/r/MacOS/comments/e5af5s/need_help_i_need_some_screenshots_of_macos/

**Comment by n4n0GH** [comment]
The plus icon on the maximize icon appears when you hold Option or Shift (I forgot) and signalizes that the window, when maximized, will be sent to a new workspace in full screen mode. If you hover over the buttons regularly you'll get the usual triangular shapes.

**Comment by kupiqu** [comment]
> The plus icon on the maximize icon appears when you hold Option or Shift (I forgot) and signalizes that the window, when maximized, will be sent to a new workspace in full screen mode. If you hover over the buttons regularly you'll get the usual triangular shapes.

I see, thanks for the information.

**Comment by trmdi** [comment]
FWIW I've also wanted to bring this into this Firefox theme: https://github.com/vinceliuice/Mojave-gtk-theme/pull/88
:)

**Comment by kupiqu** [comment]
@trmdi I think it would be nicer and more appropriate that the hint of buttons on the right is independent of the hint of buttons on the left, and vice versa. Would you agree? If so, could you please submit a pull request implementing this? I would do it myself but you know better the internals of the unison hovering implementation.

If you are consider doing this, please note that I have just added upstream changes from the breeze theme (06441817cebca3e959b6197ed072851fcd57d910) that affect how animations are implemented, so it would be great if your pull request is made on top of V0.8.9.

Thanks in advance.

**Comment by trmdi** [comment]
I like the current more because it displays all hints with just one hovering.
Could you tell us how this works on macOS? @n4n0GH

**Comment by kupiqu** [comment]
I ignore if macOS shows (or can show) buttons on the right (I naively thought they are shown on the left only, because it's what I typically see), @n4n0GH will know better...

My rationale anyway is that if a user sets buttons on the right and on the left, it is likely that they are located for a reason and they are meant differently (belonging to a different category), hence displaying all icons at once is more noise than signal IMO for a typical use case. 

I may reconsider this if it is any different in macOS, but otherwise, I think I will implement this based on a `less is more` motive.

**Comment by trmdi** [comment]
What if it's not his computer?

**Comment by kupiqu** [comment]
> What if it's not his computer?

If a user is unfamiliar with current system settings of a (plasma) session, I frankly think this will be the least of the problems. Also, it is likely that such a user will use a guest (plasma) session anyway, or if it is sth fast that does not require changing user sessions, it will then likely have a familiar user by the side.

In addition to that, I don't think the main role of unison hovering in macOS is (only) informative, but (also) to show a smooth behavior, as moving the mouse it's not always that precise, and moving in or out just 1px may change the display and be disruptive.

Tri-state could certainly be an option, but I personally find it unnecessary here if only based on familiarity. Do you really think exploring left and right, if a user is unfamiliar, would be that disruptive and workflow breaker? The user probably doesn't have workfows in an unknown computer anyways...

Perhaps it is more a matter of taste. I can understand that we, as users, may prefer differently.

**Comment by n4n0GH** [comment]
So the problem is that macOS only has three buttons anymore that should be of concern to the user. They used to have an additional pill-shaped button to shade windows, but afaik that hasn't been a thing since quite a few iterations.

Usually when hovering over any button, all buttons receive the hover state. However this may be translated to buttons that can be freely placed on the titlebar by users, I'm not sure. It would make sense to have it only be active on the part of the buttons the user is actually hovering on I guess. Maybe.

**Comment by kupiqu** [comment]
Thank you @n4n0GH for the feedback

> It would make sense to have it only be active on the part of the buttons the user is actually hovering on I guess. Maybe.

That's how I see it, but @trmdi sees it differently, and it's fine.

I may change how this works in SBE, but will see, I don't have time to work on this at the moment anyway.

If in the meantime @trmdi wants to give the tri-state option a try, I'd be glad to add it, so everyone can be happy.
