### ISSUE TITLE
[Req] Option to Hide border for all maximized windows (vertically or fully maximized) 

### ISSUE THREAD

**Issue by ripefig** [kupiqu/SierraBreezeEnhanced#44]
![image](https://user-images.githubusercontent.com/45201036/69885606-08a90600-12ef-11ea-8079-c15baac000d4.png)

I'm thinking have something like this, maybe with a small transparent rectangle around the vertically/fully maximized window to separate the windows from each other and the panel (sort of like I3 gaps), as well as giving a user a bigger resize handle.

**Comment by kupiqu** [comment]
> I'm thinking have something like this

A bit specific but the infrastructure is there, so it's probably not very difficult to add that option to the three others

> maybe with a small transparent rectangle around the vertically/fully maximized window to separate the windows from each other and the panel (sort of like I3 gaps), as well as giving a user a bigger resize handle.

Sorry but no, there are diverse ways to achieve this, like having gaps from the kwin script, and/or increase the border size in SBE and/or make it transparent by making the titlebar transparent.

This so fine tune specificities are not an option for me.

**Comment by kupiqu** [comment]
> A bit specific but the infrastructure is there, so it's probably not very difficult to add that option to the three others

I implemented this as "never, maximized, any maximization (includes H/V) and always"

Will push this change soon

**Comment by kupiqu** [comment]
done 133247c332c1d04ea29f688498bc86325165e572

**Comment by patjldeiM0IP** [comment]
This doesn't seem to work for me, on v0.7.7. _Any Maximization_ gives the same result as _Maximized Windows_ in that a fully maximized window has no title bar but it remains for h/v maximization.

https://i.imgur.com/FYt1QkQ.png

Anyone able to reproduce?

**Comment by kupiqu** [comment]
I think the problem is that you're not really maximizing V/H... Not sure how you are doing it, if you are using some tilling script or sth, but this is an upstream issue.

To test how it really works in SBE, go to System Settings > Global Keyboard Shortcuts > Kwin  and there set a shortcut for H/V Maximization.

Once done, test it. This works in my system properly.

**Comment by patjldeiM0IP** [comment]
Ah, that's exactly it - I was using the _System Settings_ > _Global Keyboard Shortcuts_ > _Kwin_ > _Quick Tile Window to the Left|Right_ shortcut. Sorry for the report.

**Comment by kupiqu** [comment]
> Ah, that's exactly it - I was using the _System Settings_ > _Global Keyboard Shortcuts_ > _Kwin_ > _Quick Tile Window to the Left|Right_ shortcut. Sorry for the report.

No problem :)
