### ISSUE TITLE
Weird glitches when changing settings

### ISSUE THREAD

**Issue by kupiqu** [kupiqu/SierraBreezeEnhanced#47]
When I modify settings and borders, I need to restart kwin to avoid weird glitches.

I don't know where this comes from but would appreciate any hint from the community to know how to fix this

**Comment by kupiqu** [comment]
Will keep this open a little bit to see if users give some feedback...

**Comment by kupiqu** [comment]
@trmdi @psifidotos sorry to ping you, but I would highly appreciate some help on this. 

If you are actively using SBE and see these glitches, could you please tell?

I mad a video so you know what I talk about:

![glitches](https://user-images.githubusercontent.com/3875196/69919293-63567500-1449-11ea-90fb-47c2d28f3484.gif)

I have no clue what is causing this, so any hint would be more than appreciated!

**Comment by psifidotos** [comment]
the last days I am also noticing it, even with Breeze decoration but I dont what is its cause... There is chance that this KWin bug but I am not sure...

**Comment by kupiqu** [comment]
> the last days I am also noticing it, even with Breeze decoration but I dont what is its cause... There is chance that this KWin bug but I am not sure...

Mmm, I see. That would be a relief from my side certainly, but I wonder now if these glitches still come from SBE and somehow migrate to other Breeze themes. For instance, if one uses the option `Maximized Windows` in `Hide window title bar` that is conveyed to the Breeze theme, which does not have such an option and removes the title bar in all conditions.

For the purpose of this glitch issue here, I'd like to know if the glitches are still present if SBE is uninstalled from the system. I would do it myself, but so far I failed to see the glitches in Breeze and Breeze Enhanced.

If you recall what you changed in Breeze when you saw the glitch, I could try to reproduce it myself.

**Comment by kupiqu** [comment]
> the last days I am also noticing it, even with Breeze decoration but I dont what is its cause... There is chance that this KWin bug but I am not sure...

And thank you very much for your response, btw!

**Comment by sputniktr02** [comment]
I also have the glitches with SBE. Selecting SBE causes glitches and if you select another decoration after that, glitches are still present until you restart the system, then everything goes back to normal for other decorations.
My system:
Operating System: openSUSE Tumbleweed 20191128
KDE Plasma Version: 5.17.3
KDE Frameworks Version: 5.64.0
Qt Version: 5.13.1
Kernel Version: 5.3.12-1-default

Note: I use Kwin Low Latency if that has any effect I'm not sure

**Comment by kupiqu** [comment]
> glitches are still present until you restart the system

sorry to hear that. please execute `kwin --replace` in krunner instead as a workaround for now, you don't need to restart 

I think I will go back in time to identify the commit that introduced the issue and will fix/revert (perhaps is the hidetitlebar option that is not properly set, but will see).

**Comment by kupiqu** [comment]
I am almost convinced that the issue is in SBE and I think it is related to the options of shadows for inactive windows.

The issue was first triggered in commit 9673c5e1f1b7e0aeb7e1655bb6840e03fe6614ba but this one came from a minor bug that was fixed afterwards.

However, I didn't find the way to fix the issue once further options were introduced in commit 86f1f3f7bf5b90beb671e3d0e3865b31eb7524ab. 

I wasted so much time and ran out of ideas, so I would highly appreciate if anyone else would help on this.

**Comment by trmdi** [comment]
@kupiku

Could you write steps to reproduce it? Sometimes I change SBE settings but have not seen the problem like your video.

**Comment by kupiqu** [comment]
@trmdi, thanks for willing to help on this!

Unfortunately it is something that is not 100% reproducible, but I found out that trying to change shadow features, especially in inactive windows, usually trigger this. And playing with shadow colors and inactive shadow settings are the ones that more frequently do so.

So:

1. open SBE settings
2. modify shadow options, in particular enabling/disabling specific shadow of inactive windows and/or the colors of the shadows
3. apply the change
4. if you then visualize a small kwin glitch, then the issue is triggered, even though sometimes you need to open a new window application to realize about it

Let me know if you can reproduce...

**Comment by trmdi** [comment]
Can't reproduce it. Maybe it relates to the video driver like the button glitch issue ?

**Comment by trmdi** [comment]
BTW, I notice that after changing the shadow setting, click the Apply does not update the shadow of windows, you have to change the active state of every window to update each of them.

**Comment by trmdi** [comment]
Does it help if you add an `update()` here: https://github.com/kupiqu/SierraBreezeEnhanced/blob/51b9d9914500bf1b707b404c9bb565e1fc53f652/breezedecoration.cpp#L685 ?

**Comment by kupiqu** [comment]
> Can't reproduce it. Maybe it relates to the video driver like the button glitch issue ?

maybe, but curiously this is a different newer computer that doesn't suffer the button glitch

**Comment by kupiqu** [comment]
> Does it help if you add an `update()` here:
> 
> https://github.com/kupiqu/SierraBreezeEnhanced/blob/51b9d9914500bf1b707b404c9bb565e1fc53f652/breezedecoration.cpp#L685
> 
> ?

I have a busy day today, but will try to restore this asap

**Comment by trmdi** [comment]
> > Does it help if you add an `update()` here:
> > https://github.com/kupiqu/SierraBreezeEnhanced/blob/51b9d9914500bf1b707b404c9bb565e1fc53f652/breezedecoration.cpp#L685
> > 
> > ?
> 
> I have a busy day today, but will try to restore this asap

I think this was not here before. I mean you to try adding it. :D

**Comment by kupiqu** [comment]
Yes sorry, this was actually a response to #62 

Regarding update(), I think I tried all these combinations, but will do again for the case it is any different to what I did previously

**Comment by RRajiBB** [comment]
I have a similar issue. Sometimes the button surrounding become translucent and you can see the background. Jiggling the window or clicking outside makes it go way.
![Screenshot_20200103_231628](https://user-images.githubusercontent.com/34903858/71739843-9644bc00-2e80-11ea-8424-0bf159389597.png)

**Comment by kupiqu** [comment]
That's a different issue. Please see https://bugs.kde.org/show_bug.cgi?id=397215

You may want to try these workarounds:

- https://bugs.kde.org/show_bug.cgi?id=397215#c7
- https://bugs.kde.org/show_bug.cgi?id=397215#c15

**Comment by RRajiBB** [comment]
That was a fast reply. Thanks. Yes my issue is exactly what you linked. I'll try these.

**Comment by ray-holmium** [comment]
Can confirm I'm experiencing this issue as well. First noticed it when I enabled window borders, which caused window decorations to disappear completely. Both breeze and SBE were completely blank. This also disabled shapecorners, so all my window corners were square. Fixed it by restoring SBE settings to default, for the most part anyway. Default breeze theme is still corrupted.

**Comment by kupiqu** [comment]
as a workaround, try using https://github.com/kupiqu/SierraBreezeEnhanced/issues/47#issuecomment-560357194

**Comment by arun54321** [comment]
using **export MESA_LOADER_DRIVER_OVERRIDE=iris** as an environment variable fixes this for me.

**Comment by kupiqu** [comment]
> using **export MESA_LOADER_DRIVER_OVERRIDE=iris** (intel igpu) as an environment variable fixes this for me.

Thanks, I'm running very busy at the moment, but I will give it a try when I have a chance.

**Comment by kupiqu** [comment]
Somehow the changes introduced in the decorations for Plasma 5.18 made this issue (almost) disappear. Now I only note a mild, transient glitch in kwin when a new window is open, but no permanent issue with the decorations.

I think this may indeed be related to upstream issues with the graphics driver and kwin. So I'll close this issue. If I see further problems or somebody still sees them, I may reopen the issue.

**Comment by kupiqu** [comment]
I realized that in my system using opengl 2.0 fixes the issue. If I use 3.1 the issue comes back.

**Comment by arun54321** [comment]
> I realized that in my system using opengl 2.0 fixes the issue. If I use 3.1 the issue comes back.

Using latest mesa fixes it. It works fine even on opengl 3.1

**Comment by kupiqu** [comment]
Cool, but I think I also use the latest. What mesa version do you use? Mine is 19.2.8-0ubuntu0~18.04.3

**Comment by arun54321** [comment]
I'm using mesa git version.

**Comment by kupiqu** [comment]
> I'm using mesa git version.

Great, looking forward for next release!
