### ISSUE TITLE
[macOS] The color of the symbols shouldn't depend on the window color

### ISSUE THREAD

**Issue by trmdi** [kupiqu/SierraBreezeEnhanced#49]
Use KvMojave colorscheme and check the option "Match titlebar to window color" with the macOS theme. When hovering on the buttons of inactive windows, the symbols are very difficult to see.

Screenshot:
![image](https://user-images.githubusercontent.com/11857205/69971951-4c9c4500-1553-11ea-9557-cedcb0b497ff.png)

**Comment by trmdi** [comment]
The color should depends on the color of the button instead of the window color.

**Comment by kupiqu** [comment]
> The color should depend on the color of the button instead of the window color.

The implementation is a bit more complicated than this. I may have introduced the bug in a recent commit, give me some time to check

**Comment by kupiqu** [comment]
My mistake was to apply the same color heuristic of the SBE themes, which obviously do not apply to inactive windows in mac themes. Will fix, stay tuned.

**Comment by kupiqu** [comment]
Could you please check again?
