### ISSUE TITLE
Match title's bar to window's color feature from SierraBreeze

### ISSUE THREAD

**Issue by kupiqu** [kupiqu/SierraBreezeEnhanced#5]
Consider adding this feature, especially to be applied not only in general but also in per application basis.

This should ease specific window's titlebars matching window's backgrounds, so one doesn't have to get dirty directly editing colorthemes, specifying kwin rules, etc.

This seems particularly relevant for applications such as konsole, qView and very few others, which allow changing the background in application settings.

**Comment by kupiqu** [comment]
An update: I implemented the feature applied in general, but:

> This should ease specific window's titlebars matching window's backgrounds, so one doesn't have to get dirty directly editing colorthemes, specifying kwin rules, etc.

Unfortunately, I don't think this is really possible (or at least I don't know how). But at least it will significantly ease manually editing the colortheme, so only changing the background color (to match application background) and nothing else will just work (setting visible titlebar text and buttons in all conditions).

Need to port the feature to specific application overrides and test before uploading.

**Comment by kupiqu** [comment]
fixed with commit 9673c5e1f1b7e0aeb7e1655bb6840e03fe6614ba

> Need to port the feature to specific application overrides

will add another issue specifically for this functionality

**Comment by Petross404** [comment]
I think this feature only works when Breeze is used and not QtCurve for example. Am I wrong?

**Comment by kupiqu** [comment]
> I think this feature only works when Breeze is used and not QtCurve for example. Am I wrong?

I didn't test it in styles other than Breeze (and they are not supported, at least in principle), but I just checked it out in Fusion and QtCurve and the option seems to work just fine.

Are you seeing differently?

**Comment by Petross404** [comment]
My bad, I was using QtCurve with a slight opacity so the result wasn't correct. But konsole's titlebar is white and not dark as it should with SierraBreeze.

Is this another issue?

**Comment by kupiqu** [comment]
> But konsole's titlebar is white and not dark as it should with SierraBreeze.

- What do you mean the titlebar is white? As mentioned in the changelog and in releases, this option matches the "BackgroundNormal" color under "Windows" section of your color scheme. So the color it matches will be exactly that one.

- Are you comparing this to the SierraBreeze theme? The implementations in SierraBreezeEnhanced and in SierraBreeze are not the same.

If there is an issue wrt the above you will need to show me (screenshot).

**Comment by kupiqu** [comment]
I want to avoid adding hacks for particular applications in the code... but achieving your goal is possible following 4 steps:

1. Go to color schemes in settings and save your current color-scheme with a different name.
2. Add a kwin rule for Konsole to use that color scheme.
3. Edit the text file of the new color-scheme (located in ~/.local/share/color-schemes/) so that the "BackgroundNormal" color under "Windows" section of the color scheme matches Konsole's background color.
4. Add an override in SierraBreezeEnhanced for konsole to match its titlebar with its window background.

That's it. It seems more difficult than it actually is... please give it a try. If you don't know how to complete a particular step, let me know and will try to be more explicit.
