### ISSUE TITLE
[macOS] The size of buttons like "Keep above" when clicked is bigger than other buttons

### ISSUE THREAD

**Issue by trmdi** [kupiqu/SierraBreezeEnhanced#50]
Please see the screenshot:
![image](https://user-images.githubusercontent.com/11857205/69971446-7e60dc00-1552-11ea-8d17-c5418b0371ee.png)

I think the size should be consistent.

**Comment by kupiqu** [comment]
That's because of the animation. 

Are you suggesting to remove the oversize once clicked? I sort of liked it to emphasize the check

**Comment by trmdi** [comment]
No, I turned off the animation.
And I suggest to use the same size when not hovering. Because when checked that button, we have the symbol shown so the bigger size is not necessary.

**Comment by kupiqu** [comment]
Yeah, at the very least I should deal with it when the animation is off, but I think I will keep it otherwise

**Comment by trmdi** [comment]
I meant just use this:
https://github.com/kupiqu/SierraBreezeEnhanced/blob/aeb32537ab9a36319faafcdb9ee547055bf2e000/breezebutton.cpp#L763-L766
and remove the below lines:

**Comment by kupiqu** [comment]
Yes, I understood

**Comment by kupiqu** [comment]
Done :)

**Comment by trmdi** [comment]
Ah, now I got your idea. Thank you! :)

**Comment by kupiqu** [comment]
Thank you for catching these issues :)
