### ISSUE TITLE
Provide more smooth unison hovering

### ISSUE THREAD

**Issue by gikari** [kupiqu/SierraBreezeEnhanced#54]
Currently unison is triggered only if any of the buttons is hovered, however not the space between them.
![sbe_buttons](https://user-images.githubusercontent.com/14205339/70183051-f6f3a400-16dc-11ea-87ed-f54549664db5.gif)

In macOS buttons unison hovering is triggered when **the area** occupied by button group is hovered.
![macos_buttons](https://user-images.githubusercontent.com/14205339/70183796-5aca9c80-16de-11ea-8388-7d971be5df67.gif)

macOS behavior is more smooth, because it avoids blinking, when moving cursor between buttons, so it would be great if the same smooth behavior would be implemented in SBE.

**Comment by kupiqu** [comment]
Mmm, that is quite trickier than it seems, it would need to create some sort of new pseudo-butons in the decoration that take all the space of left and right buttons, respectively, only for the purpose of detecting hovering within the area... That is, a lot of deviation from upstream Breeze.

Not sure it's worth it. Pinning @trmdi, who implemented this.

**Comment by trmdi** [comment]
IIRC there is a ButtonGroup class. Not sure if it helps. Busy now with hacking Latte. :D

**Comment by kupiqu** [comment]
> IIRC there is a ButtonGroup class. Not sure if it helps. Busy now with hacking Latte. :D

Sure, no problem. Leaving this open for the case somebody wants to deal with this...

**Comment by kupiqu** [comment]
> IIRC there is a ButtonGroup class. Not sure if it helps. Busy now with hacking Latte. :D

Just for curiosity, what are you working on in latte? :)

**Comment by trmdi** [comment]
> > IIRC there is a ButtonGroup class. Not sure if it helps. Busy now with hacking Latte. :D
> 
> Just for curiosity, what are you working on in latte? :)

I'm trying to fixing the bug that desktop icons are overlapped by Latte panel/dock.
