### ISSUE TITLE
Remove option for titlebar fonts

### ISSUE THREAD

**Issue by gikari** [kupiqu/SierraBreezeEnhanced#57]
Kde Plasma already has settings for font specifically for title bar:
![Plasma_Font_Settings](https://user-images.githubusercontent.com/14205339/70458696-8c5eb180-1aaa-11ea-9c20-2ab4a9d075f0.png)

SBE also has font settings:
![SBE_fonts](https://user-images.githubusercontent.com/14205339/70458842-e3fd1d00-1aaa-11ea-8b2a-fa869bc5a73e.png)

Therefore it is redundant and takes a lot of vertical space, making it hard to hit OK button on standard 15" laptop 1080p screen with 125% scaling and quite common macOS layout .
![Screenshot_20191209_204627](https://user-images.githubusercontent.com/14205339/70459338-e0b66100-1aab-11ea-969a-8edba326d1b4.png)

Giving all of this, I think font configuration should be removed from decorations settings. Font settings should be grabbed from plasma fonts settings.

**Comment by kupiqu** [comment]
Mmm, this was done originally in Breeze Enhanced, perhaps to allow LXQt users to have access to that information, but not really sure.

I am tempted to follow your indication as you are right, it's definitely a too long list of settings.

If then somebody not using plasma complains, this could be restored but moved to a second tab and use plasma's by default, yet allowing the users to override the plasma setting in that tab if wanted.

**Comment by kupiqu** [comment]
Fixed in V0.8.5
