### ISSUE TITLE
Failing to build on launchpad

### ISSUE THREAD

**Issue by krisives** [kupiqu/SierraBreezeEnhanced#59]
Recently the PPA has stopped building with this [build log](https://launchpadlibrarian.net/455157237/buildlog_ubuntu-bionic-amd64.sierrabreezeenhanced_1.V0.8.5-0~201912110302~rev135~pkg21~ubuntu18.04.1_BUILDING.txt.gz)

It appears to be this:

```
/<<PKGBUILDDIR>>/breezedecoration.cpp: In member function ‘virtual void Breeze::Decoration::hoverMoveEvent(QHoverEvent*)’:
/<<PKGBUILDDIR>>/breezedecoration.cpp:368:33: error: ‘class KDecoration2::DecorationButton’ has no member named ‘contains’
                     if (button->contains(event->posF())) {
                                 ^~~~~~~~
```

Any ideas?

**Comment by kupiqu** [comment]
This is related to the unison hovering feature recently added by @trmdi

Perhaps there is sth that needs to be adjusted somewhere... 

@trmdi, do you have a clue? did you have to modify anything to be able to continue building SBE packages for openSUSE?

**Comment by trmdi** [comment]
Ah yes, it failed on Leep too, but not on Tumbleweed: https://build.opensuse.org/package/show/home:trmdi/SierraBreezeEnhanced

**Comment by kupiqu** [comment]
Mmm, interesting... and weird, I would expect to work or fail in both

**Comment by trmdi** [comment]
Maybe the compiler on Tumbleweed is clever than the one in Leap. 😁

**Comment by kupiqu** [comment]
I am not very familiar with package compilation, but isn't it strange that the hoverMoveEvent function is considered virtual when it is not?

`/<<PKGBUILDDIR>>/breezedecoration.cpp: In member function ‘virtual void Breeze::Decoration::hoverMoveEvent(QHoverEvent*)’:`

**Comment by krisives** [comment]
As far as I can tell `contains` was not added to `DecorationButton` until KDE 5.14. This is probably why it fails to build on those servers. Looking closer at the build recipe on Launchpad it's succeeding on all but 18.04 (Bionic) since that's the only version that is too old. However, that's also an LTS version and the one that KDE Neon is based on. While Neon itself has a much newer version of KDE installed over the base 18.04 packages, the build server itself doesn't have those packages.

**Comment by kupiqu** [comment]
oh, I see

**Comment by krisives** [comment]
For what it's worth the `DecorationButton` itself simply defines `contains` as:

```
return d->geometry.toRect().contains(pos.toPoint());
```

https://github.com/KDE/kdecoration/blob/771ed0c4f8c21674ec558102001507bc9bbde3d0/src/decorationbutton.cpp#L450

**Comment by krisives** [comment]
Also in @n4n0GH's "hello" package he ended up using `geometry().contains` which is effectively the same thing except I think it's doing floating point comparisons.

https://github.com/n4n0GH/hello/commit/fb188ce8c0d5c38a4672067cd09164c2f5b18f7c

**Comment by kupiqu** [comment]
well, I think the conditional was simply omitted, wasn't it? 

@trmdi what is that conditional controling for exactly?

```
if (button->contains(event->posF())) {
    buttonContains = true;
    break;
}
```

**Comment by kupiqu** [comment]
It seems to me that the conditional is always true beause of the parent conditional with groupContains, maybe that is why it was removed in Hello

**Comment by kupiqu** [comment]
Just removed it and works the same, so I will push the change in close this as fixed...

**Comment by trmdi** [comment]
> It seems to me that the conditional is always true because of the parent conditional with groupContains, maybe that is why it was removed in Hello

No, it's when you move the mouse into the space between buttons. Please revert this.

**Comment by kupiqu** [comment]
> No, it's when you move the mouse into the space between buttons. Please revert this.

It's working for me just fine. Did you test?

**Comment by trmdi** [comment]
> > No, it's when you move the mouse into the space between buttons. Please revert this.
> 
> It's working for me just fine. Did you test?

Try set the space between buttons to e.g. 20px. You would see it.

**Comment by kupiqu** [comment]
> Try setting the space between buttons to e.g. 20px. You would see it.

It works here

**Comment by trmdi** [comment]
No, that is my intention. When you hover the mouse into the SPACE but NOT the button, that is when buttonContains = false;

**Comment by kupiqu** [comment]
Wait, wasn't the purpose to have it enabled also in the space within buttons?

**Comment by trmdi** [comment]
No, it's enabled ONLY when you hover on a button.

**Comment by kupiqu** [comment]
Ok I think I understand now, so to enable one needs to hover a button and to disable one needs to escape that region, is that what you mean?

**Comment by trmdi** [comment]
Yes. That's my intention.

**Comment by n4n0GH** [comment]
That's not how it works on macOS though. Might want to keep that in mind.

**Comment by kupiqu** [comment]
I see.

But mmm, I think I like the region for both actually, whether or not this is used in macOS, and furthermore if it is...

Thanks @n4n0GH for the input, btw! I was in the middle of writing this down and edited accordingly :)

**Comment by n4n0GH** [comment]
In general if you have questions about macOS behavior feel free to hit me up, I got a machine running Mojave and can give you screenshots and whatnot if you need.

**Comment by kupiqu** [comment]
> In general if you have questions about macOS behavior feel free to hit me up, I got a machine running Mojave and can give you screenshots and whatnot if you need.

awesome, thank you

**Comment by trmdi** [comment]
Ok, that is not a big problem.

**Comment by trmdi** [comment]
Also remove the for loop, it's no needed if you don't check that.

**Comment by kupiqu** [comment]
> Also remove the for loop, it's no needed if you don't check that.

good catch
