### ISSUE TITLE
Feature Request: Option to keep title bars dark or light mode

### ISSUE THREAD

**Issue by jcfrosty** [kupiqu/SierraBreezeEnhanced#6]
It would be pretty awesome to have the title bar be able to keep the light style or dark style without them changing due active/inactive status. I really kind of like the light style all to itself and have a lighter color theme cause the dark title bar to clash.

**Comment by kupiqu** [comment]
Don't you think this is better managed by issue #5 ?

1. I mean, even if I'd create a light vs dark theme, that would be in conflict if you use a different light color theme. In contrast, having the match of title bar with respect to window's color applied in general would solve your request for any color theme.

2. Issue #5 is also intented be applied only to specific applications, for instance when a user wants vanilla breeze, but a complete dark theme, for e.g., konsole or qView...

I'm closing this issue now. Please reopen if usercase (1) above does not account for what you are looking for, and if so, please tell me how is that.
