### ISSUE TITLE
Changing the shadow setting does not update the shadow immediately

### ISSUE THREAD

**Issue by trmdi** [kupiqu/SierraBreezeEnhanced#62]
When trying to reproduce the bug #47 I've noticed that after changing the shadow setting, the shadow of windows are not updated immediately, you have to change the active state of every window to update each of them.

Expected result:
- After changing it, the decoration updates itself immediately.

**Comment by kupiqu** [comment]
This is is something I temporarily changed to see if that fixed the issue,
and did not, and forgot to reverse, actually.

**Comment by trmdi** [comment]
What commit are you reffering to?

**Comment by kupiqu** [comment]
Yes, will do asap

**Comment by kupiqu** [comment]
I think it should be fixed now. Could you please test this out again and let me know if this still fails for you?

**Comment by trmdi** [comment]
I think you still forgot to uncomment this line:
https://github.com/kupiqu/SierraBreezeEnhanced/blob/1d9aa6f47b6c9404a9e9176d8ef31483bc34905b/breezedecoration.cpp#L680

**Comment by kupiqu** [comment]
right! :)
