### ISSUE TITLE
Please add a toggle for the stroke border around the buttons

### ISSUE THREAD

**Issue by ryu-ketsueki** [kupiqu/SierraBreezeEnhanced#64]
For the borders on the buttons on macOS Sierra and macOS Dark Aurorae, they could've been optional instead of be enabled all the time. The original BreezeEnhanced doesn't have them and I prefer the buttons as a solid color without border. Couldn't there be an option to have the stroke borders or not?

This is how they are:
![2019-12-20_20-54_1](https://user-images.githubusercontent.com/39316730/71299327-9d8da500-236b-11ea-82f7-5d8530f56575.png)
![2019-12-20_20-54](https://user-images.githubusercontent.com/39316730/71299328-9e263b80-236b-11ea-8ab9-2c6cac45f0d1.png)

And this is how they could be:
![2019-12-20_20-56](https://user-images.githubusercontent.com/39316730/71299338-ae3e1b00-236b-11ea-8e71-e115dcc59db3.png)
![2019-12-20_20-55](https://user-images.githubusercontent.com/39316730/71299337-ae3e1b00-236b-11ea-8458-3acb09bd6e10.png)

**Comment by kupiqu** [comment]
I think macOS uses outlines, doesn't it?

**Comment by ryu-ketsueki** [comment]
> I think macOS uses outlines, doesn't it?

I don't think so. I've used macOS Yosemite and I just had a look on the newer versions and none of them have outlines on the buttons like that. If they do, they are hard to notice. But even if they did, couldn't there be an option to toggle the outlines or not, making them optional? See how those buttons look better without the outlines with the original BreezeEnhanced. I would use SierraBreezeEnhanced instead of the original BreezeEnhanced because of the customization options it gives that BreezeEnhanced doesn't, like the Active/Inactive shadow color being separate.

**Comment by kupiqu** [comment]
Please see #23 

Giving an option for this is not that easy and there are already many options. If you like BreezeEnhanced better, you could request there to have specific incative shadows...

**Comment by kupiqu** [comment]
See also issue #40. If there is sth to further improve in that regard I may be open to that...

**Comment by ryu-ketsueki** [comment]
It's why I had suggested to add an option to make it optional. Some people like, some people dislike, you could please both by adding an option to enable/disable it or to increase/reduce the contrast between the button and the outline.

And there are more features on SierraBreezeEnhanced I prever over the original BreezeEnhanced, like the unison hovering to show the icons inside the buttons where BreezeEnhanced doesn't even show the icons. I see this is a repeated issue but I believe it is of best interest to add this as option, even if there are too many already, so both sides may enjoy it. Same for Horizontal Margin. Could be brought back.

**Comment by kupiqu** [comment]
My time for this is spare, and what you ask requires some time. 

In addition, I don't want to bloat the settings with exponentially growing options; all users have their own preferences, really, but everything cannot be an option.

I am, however, open to review pull requests. If interested, I would suggest to create a setting for the outlines in the [0, 100] range to control how much darker (or lighter for dark backgrounds) the outline vs. the filled color should appear.
