### ISSUE TITLE
Bug: Reduced background opacity blurs rounded corners.

### ISSUE THREAD

**Issue by toluschr** [kupiqu/SierraBreezeEnhanced#69]
### Issue
Rounded Corners don't change the area that gets blurred.
![21:24:16](https://user-images.githubusercontent.com/44272603/77234873-f27ec880-6bb1-11ea-906a-61ce43f746b9.png)

### How to reproduce
Set the Corner Rounding to something high, like 15px and enable transparency.

**Comment by kupiqu** [comment]
This is an upstream issue

**Comment by kupiqu** [comment]
Please see #24

**Comment by toluschr** [comment]
Oh, I'm sorry. I thought the issue was closed (Meaning resolved.)

**Comment by kupiqu** [comment]
No problem. Unfortunately the issue is not resolved :(
