### ISSUE TITLE
Window override based on window type

### ISSUE THREAD

**Issue by beojan** [kupiqu/SierraBreezeEnhanced#7]
Namely so I can set the opacity separately for dialogs.

**Comment by kupiqu** [comment]
I'm sorry but this is probably better a feature request bug to the vanilla Breeze theme.

**Comment by kupiqu** [comment]
Also, I don't know if I would have the skills to add this feature... I need to add a couple of features to overrides in the near future. If I would see a way to implement this, I would reopen. I hope it is ok. 

In the meantime, I would encourage submitting the feature request to vanilla Breeze in kde bug, as well as to BreezeEnhanced and SierraBreeze in github.

Perhaps they know a clever way to add this functionality, which I could then port to SierraBreezeEnhanced.
