### ISSUE TITLE
Include aur package in readme

### ISSUE THREAD

**Issue by gsbhasin123** [kupiqu/SierraBreezeEnhanced#71]
https://aur.archlinux.org/packages/kwin-decoration-sierra-breeze-enhanced-git/

**Comment by kupiqu** [comment]
I modified it a little bit please take a look

**Comment by gsbhasin123** [comment]
I don't think it should be in a codeblock since it's not a command...
:thinking:

**Comment by kupiqu** [comment]
Right, but it doesn't look good otherwise due to indentation, unfortunately

Is there a direct command you could set?

**Comment by gsbhasin123** [comment]
> Right, but it doesn't look good otherwise due to indentation, unfortunately

Ah.

> Is there a direct command you could set?

Sure! lemme do that

**Comment by gsbhasin123** [comment]
Fixed by `92ca8c5d773221efdfab81565dc3086f02f5a97f`

**Comment by kupiqu** [comment]
Thanks!
