### ISSUE TITLE
Restore button on "Dark Aurorae Monochrome Symbols" could be clearer

### ISSUE THREAD

**Issue by gsbhasin123** [kupiqu/SierraBreezeEnhanced#74]
The restore button kinda looks like a maximize button to be honest. 
look at windows' for an example of a better implemented one :P

**Comment by gsbhasin123** [comment]
Also sorry for opening so many issues haha

**Comment by kupiqu** [comment]
> The restore button kinda looks like a maximize button to be honest.
> look at windows' for an example of a better implemented one :P

isn't it how dark aurorae is?

https://store.kde.org/p/1183298
https://github.com/bolimage/Dark-Aurorae

**Comment by gsbhasin123** [comment]
oh, it was supposed to resemble that? didn't know
Anyways, wouldn't a custom change, maybe a slight shadow of a second rectangle, be nice?  
:thinking:

**Comment by kupiqu** [comment]
Don't plan to change Dark Aurorae because it's how it is, but I'm open to consider pull requests for other styles ;-)
