### ISSUE TITLE
Adaptive color mode should support blur

### ISSUE THREAD

**Issue by gsbhasin123** [kupiqu/SierraBreezeEnhanced#76]
Take the sierrabreeze (NOT SBE, a project that just happens to have a similar name, unless you have any affiliation with it)decoration, it supports blur if the window is blurred (eg in konsole).

See: https://github.com/ishovkun/SierraBreeze for an example on how to implement this (if someone can point me to the relevant lines of code in sierrabreeze, ill try making a pr)

**Comment by kupiqu** [comment]
Please see https://github.com/kupiqu/SierraBreezeEnhanced/issues/5#issuecomment-445437687

**Comment by gsbhasin123** [comment]
Ah so how would I achieve window decoration blur?

**Comment by gsbhasin123** [comment]
Per-app or globally. I'm not quite sure what the instructions tell me to do.
Normally for overriding an app's window decoration color I create a new colorscheme & use kde's gui to edit it

**Comment by kupiqu** [comment]
> Per-app or globally.

Sierra Breeze only hard-codes it for Konsole

> I'm not quite sure what the instructions tell me to do.

You just need to do that that you said:

> Normally for overriding an app's window decoration color I create a new colorscheme & use kde's gui to edit it

Then ensure that both konsole's profile and its decoration (override) have the same opacity (that's why you need the override if you don't have that opacity in general for all apps)

**Comment by gsbhasin123** [comment]
Ah, okay, but I don't see any opacity fields in the colors section (sorry for being stupid, i'm just confused XD)

**Comment by kupiqu** [comment]
I am also confused :)

Do you want the title bar of konsole to have the same of color and transparency of its terminal, right?

- For the color part: edit the colorscheme accordingly (just as you mentioned) and apply it to konsole with a kwin rule

- For transparency: look which one you have it in konsole's profile and apply it to konsole override inside SBE settings (note that opacity is 1-transparency)

**Comment by gsbhasin123** [comment]
perfecto!
![image](https://user-images.githubusercontent.com/48339289/78925369-2b42ec80-7a50-11ea-8c45-9159d214fef1.png)

Thanks :)

Anyways what I was originally proposing is to have it auto detect the blur but eh this actually gives me more control TBH

**Comment by kupiqu** [comment]
> Never mind I found it haha
> ![image](https://user-images.githubusercontent.com/48339289/78923904-c5556580-7a4d-11ea-8964-ffafa4e54ce7.png)

That's exactly what I meant 😃

**Comment by kupiqu** [comment]
> Anyways what I was originally proposing is o have it auto detect the blur

That's unfortunately not possible (Sierra Breeze does it only for Konsole as a hack)

**Comment by gsbhasin123** [comment]
Ah i see :) 
Thank you
