### ISSUE TITLE
Error when cmake command

### ISSUE THREAD

**Issue by dedicahyadi** [kupiqu/SierraBreezeEnhanced#8]
please help me, what should i do. i am using kde neon. thanks
[CMakeOutput.log](https://github.com/kupiqu/SierraBreezeEnhanced/files/2628933/CMakeOutput.log)
[CMakeOutput.log.txt](https://github.com/kupiqu/SierraBreezeEnhanced/files/2628935/CMakeOutput.log.txt)

CMake Error at CMakeLists.txt:24 (find_package):
  By not providing "FindKDecoration2.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "KDecoration2", but CMake did not find one.

  Could not find a package configuration file provided by "KDecoration2" with
  any of the following names:

    KDecoration2Config.cmake
    kdecoration2-config.cmake

**Comment by kupiqu** [comment]
You need to install libkdecorations2-dev.

**Comment by dedicahyadi** [comment]
thanks, but there is another erros.

-- Could NOT find KF5CoreAddons (missing: KF5CoreAddons_DIR)
-- Could NOT find KF5CoreAddons: found neither KF5CoreAddonsConfig.cmake nor kf5coreaddons-config.cmake 
-- Could NOT find KF5GuiAddons (missing: KF5GuiAddons_DIR)
-- Could NOT find KF5GuiAddons: found neither KF5GuiAddonsConfig.cmake nor kf5guiaddons-config.cmake 
-- Could NOT find KF5ConfigWidgets (missing: KF5ConfigWidgets_DIR)
-- Could NOT find KF5ConfigWidgets: found neither KF5ConfigWidgetsConfig.cmake nor kf5configwidgets-config.cmake 
-- Could NOT find KF5WindowSystem (missing: KF5WindowSystem_DIR)
-- Could NOT find KF5WindowSystem: found neither KF5WindowSystemConfig.cmake nor kf5windowsystem-config.cmake 
-- Could NOT find KF5I18n (missing: KF5I18n_DIR)
-- Could NOT find KF5I18n: found neither KF5I18nConfig.cmake nor kf5i18n-config.cmake 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: CoreAddons GuiAddons ConfigWidgets
  WindowSystem I18n)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:30 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/dedi/Downloads/SierraBreezeEnhanced-0.2/build/CMakeFiles/CMakeOutput.log".

**Comment by kupiqu** [comment]
Just follow these directions and see if it helps:

For every error, e.g. KF5CoreAddons, set them to small letters and look for packages (e.g. apt-cache search kf5coreaddons), then install the lib dev package (e.g., libkf5coreaddons-dev).

Once all dependencies are fixed, you will be able to compile.

**Comment by uvwild** [comment]
having participated in a c++ project recently, I wonder why the C++ world still has not found a clean way to specify dependencies. 
It is still pretty much like  "it works for me"  (because I secretly installed all the dependencies and forgot which ones ;)
Every time I have to rebuild something from C-source, I have to hunt down the correct name for the installer of my distro.
This did not change much since the 1990's except that its a bit easier to find the dep libs, since somebody else asked the question before....
