### ISSUE TITLE
There is extra padding outside the rounded border

### ISSUE THREAD

**Issue by Hentioe** [kupiqu/SierraBreezeEnhanced#80]
In order to show the problem more clearly, I set the corner radius value to 40px.

This is normal:

![image](https://user-images.githubusercontent.com/13946976/89547381-42e08500-d838-11ea-995b-9b963212644e.png)

Here is the problem:

![image](https://user-images.githubusercontent.com/13946976/89547722-aff41a80-d838-11ea-87fd-a2786d549da0.png)

As the screenshot shows, I just moved the window position to the right.

This is my setting:

![image](https://user-images.githubusercontent.com/13946976/89549116-7cb28b00-d83a-11ea-944c-2d4dec801f42.png)

Is this normal?

This detail makes me uncomfortable.

**Comment by kupiqu** [comment]
Please see #24
