### ISSUE TITLE
Button size is tiny in GTK apps

### ISSUE THREAD

**Issue by taprobane99** [kupiqu/SierraBreezeEnhanced#82]
please consider a fix like this, as currently size is very small in Firefox etc. on KDE Plasma

https://github.com/Zren/material-decoration/commit/master

**Comment by kupiqu** [comment]
Can you share a screenshot of the issue so I can test?

**Comment by taprobane99** [comment]
<img width="95" alt="Screenshot_20201106_091902" src="https://user-images.githubusercontent.com/57266492/98348967-4f2fd600-2011-11eb-861f-64f230a3ee5c.png">

**Comment by taprobane99** [comment]
top is Firefox, bottom is Dolphin file browser. seems to be about 8x8 pix vs 14x14 pix.

**Comment by kupiqu** [comment]
> top is Firefox, bottom is Dolphin file browser. seems to be about 8x8 pix vs 14x14 pix.

It's a bit weird though, as I use Firefox and other gtk apps, and I don't notice this issue :/

**Comment by taprobane99** [comment]
there is a discussion of the bug here. at the moment it seems to be only fixable by each theme creator:

https://bugs.kde.org/show_bug.cgi?id=426074#c6

**Comment by kupiqu** [comment]
I think this needs to be fixed upstream in Breeze
