### ISSUE TITLE
Margin instead of padding

### ISSUE THREAD

**Issue by susonthapa** [kupiqu/SierraBreezeEnhanced#85]
I think it would be better to give option to set margin instead of padding. When I set the padding (which I have to, in order to get the required height of the title bar) then the button activates when my cursor is near the border between title bar and the application. This causes accidental clicks when I try access menus in the application. 

I couldn't actually capture the cursor but I hope you will get the idea
![image](https://user-images.githubusercontent.com/33973551/108009450-dcc88c00-702a-11eb-839a-05366772cc2a.png)

If I use the breeze window decorations then the button is only active when I hover above it.

**Comment by kupiqu** [comment]
You're right. Would you submit a pull request?

**Comment by kupiqu** [comment]
I'll set this as a low priority bug for now, maybe somebody picks it up.

**Comment by kupiqu** [comment]
My aim is that SBE is maintained by the community. This shouldn't be hard to fix. I hope someone in the community cares about SBE and submits a pull request about it...

**Comment by susonthapa** [comment]
I would be more than happy to contribute. But I don't know much about QT as I'm a mobile developer. Still, If I get some free time I will look into it.
