### ISSUE TITLE
Ubuntu prebuilt package no longer working

### ISSUE THREAD

**Issue by FunWithUrban** [kupiqu/SierraBreezeEnhanced#86]
Following the instructions I successfully added the repository and updated but when when trying to install the package I receive the error "Unable to locate package sierrabreezeenhanced".

I'm running Kubuntu 20.10 if that helps.

**Comment by kupiqu** [comment]
I don't manage the ppa, please send krisives a message in launchpad

**Comment by krisives** [comment]
Hey thanks. Any idea what is going wrong here:

https://launchpadlibrarian.net/532870392/buildlog_ubuntu-focal-amd64.sierrabreezeenhanced_1.V1.0.0-0~202104101803~rev164~pkg21~ubuntu20.04.1_BUILDING.txt.gz

Maybe this is it?

```
-- Could NOT find KF5IconThemes: found neither KF5IconThemesConfig.cmake nor kf5iconthemes-config.cmake 
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find KF5 (missing: IconThemes) (found version "5.68.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:30 (find_package)
```

Have the dependencies changed ever?
