### ISSUE TITLE
Spacing is not consistent across DPIs

### ISSUE THREAD

**Issue by paulmcauley** [kupiqu/SierraBreezeEnhanced#89]
I had a look through your source code, and noticed that you had stripped out the s->smallSpacing() factor from your spacing/padding/offset. You need this factor so that the spacing is consistent across multiple DPIs. You can see how I did it in my ClassikStyles decoration at https://github.com/paulmcauley/classikstyles

You can also multiply the corner radius by the s->smallSpacing() factor to get a consistent corner radius across DPIs

**Comment by kupiqu** [comment]
hey, thank you very much for pointing this out. unfortunately I don't have much time lately to work on SBE...

I'll set this as a low priority bug for now, maybe somebody picks it up.

**Comment by kupiqu** [comment]
My aim is that SBE is maintained by the community. This should be super easy to fix. I hope someone in the community cares about SBE and submits a pull request about it...
