### ISSUE TITLE
SBE writes config into Breeze's breezerc file

### ISSUE THREAD

**Issue by paulmcauley** [kupiqu/SierraBreezeEnhanced#90]
The SBE config is stored in ~/.config/breezerc . This file is meant for Breeze's settings!! You can give your settings a unique name instead by editing breezesettingsdata.kcfg and changing `<kcfgfile name="breezerc"/>` to something unique!

**Comment by kupiqu** [comment]
That's a good catch, thanks!

fixed with 8350fef58f438f5d9bb0e9a70d0c74f5c5642c82
