### ISSUE TITLE
[Feature Request] Add LIM support.

### ISSUE THREAD

**Issue by baduhai** [kupiqu/SierraBreezeEnhanced#95]
It'd be nice to have LIM support as is available on Zren's [material-decoration](https://github.com/Zren/material-decoration/tree/master/src).

**Comment by baduhai** [comment]
Preliminary suppor for LIM has been added to breeze on this [repo](https://invent.kde.org/agrinev/breeze/-/tree/lim/kdecoration).

**Comment by CavaleriOmar** [comment]
> Il supporto preliminare per LIM è stato aggiunto a brezza su questo [repository ](https://invent.kde.org/agrinev/breeze/-/tree/lim/kdecoration).

Does this mean that you can already use LIM with SierraBreezeEnhanced?

**Comment by kupiqu** [comment]
The repo is not actively maintained anymore. Pull requests welcome

**Comment by kupiqu** [comment]
duplicate of #79
