### ISSUE TITLE
Border Colors Not Respected From ~/.config/kdeglobals

### ISSUE THREAD

**Issue by Nano-Ocelot** [kupiqu/SierraBreezeEnhanced#96]
In the default Breeze Decoration you can edit ~/.config/kdeglobals to customize border colors for active and inactive windows but these colors don't work with Sierra Breeze. It would be nice to restore this functionality for those that hide the title bar. Combined with the shadow customization for inactive windows this could be a beautiful effect. Could either this functionality be supported through ~/.config/kdeglobals like Breeze or even better, could this be a configurable option in the settings menu?

**Comment by ZJsheep** [comment]
same suggestion

**Comment by kupiqu** [comment]
Please see https://github.com/kupiqu/SierraBreezeEnhanced/blob/master/README.md

https://github.com/kupiqu/SierraBreezeEnhanced/blob/master/README.md#L1-L4

**Comment by Nano-Ocelot** [comment]
I'm confused, I don't see anything about border colors in the readme or in the options. Am I missing something?

**Comment by kupiqu** [comment]
Indeed. I just wanted to note that maintainance of SBE is **discontinued**

**Comment by Nano-Ocelot** [comment]
Oh, I see. Thank you

**Comment by kupiqu** [comment]
Pull requests are always welcome

**Comment by kupiqu** [comment]
This works if you don't enable the option "match title bar to window color"
